#!/usr/bin/python3
# This file is part of Osgende
# Copyright (C) 2011-15 Sarah Hoffmann
#
# This is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
"""
 CherryPi tile server for tile databases generated with osgende-mapgen.
"""

import os
import sys
from threading import Lock
from math import pi,exp,atan

import cherrypy
import mapnik

DEFAULT_TESTMAP="""\
<!DOCTYPE html>
<html>
<head>
    <title>Testmap - %(style)s</title>
    <link rel="stylesheet" href="%(leaflet_path)s/leaflet.css" />
</head>
<body >
    <div id="map" style="position: absolute; width: 99%%; height: 97%%"></div>

    <script src="%(leaflet_path)s/leaflet.js"></script>
    <script>
        var map = L.map('map').setView([47.3317, 8.5017], 13);

        L.tileLayer('http://a.tile.openstreetmap.org/{z}/{x}/{y}.png', {
            maxZoom: 18,
        }).addTo(map);
        L.tileLayer('%(script_name)s/%(style)s/{z}/{x}/{y}.png', {
            maxZoom: 18,
        }).addTo(map);
    </script>
</body>
</html>
"""

RAD_TO_DEG = 180/pi

class TileProjection:
    def __init__(self,levels=18):
        self.Bc = []
        self.Cc = []
        self.zc = []
        self.Ac = []
        c = 256
        for d in range(0,levels + 1):
            e = c/2;
            self.Bc.append(c/360.0)
            self.Cc.append(c/(2 * pi))
            self.zc.append((e,e))
            self.Ac.append(c)
            c *= 2

    def fromTileToLL(self, zoom, x, y):
         e = self.zc[zoom]
         f = (x*256.0 - e[0])/self.Bc[zoom]
         g = (y*256.0 - e[1])/-self.Cc[zoom]
         h = RAD_TO_DEG * ( 2 * atan(exp(g)) - 0.5 * pi)
         return (f,h)


def mk_tileid(zoom, x, y):
    """Create a unique 64 bit tile ID.
       Works up to zoom level 24."
    """
    return zoom + (x << 5) + (y << (5 + zoom))


class DummyCache(object):
    """ A tile cache that does not remember any tiles. 

        Useful when testing out a new style.
    """
    def __init__(self, config):
        pass

    def get(self, zoom, x, y, fmt):
        return None

    def set(self, zoom, x, y, fmt, image=None):
        pass


class PostgresCache(object):
    """ A cache that saves tiles in postgres.
    """

    def __init__(self, config):
        self.empty = {}
        for fmt, fname in config['empty_tile'].items():
            with open(fname, 'rb') as myfile:
                self.empty[fmt] = myfile.read()

        self.max_zoom = config.get('max_zoom', 100)
        self.pg = __import__('psycopg2')
        self.db = self.pg.connect(config['dba'])
        # set into autocommit mode so that tiles still can be
        # read while the db is updated
        self.db.autocommit = True

        c = self.db.cursor()
        c.execute("SET synchronous_commit TO OFF")
        c.execute("PREPARE get_tile(bigint) AS SELECT pixbuf FROM %s WHERE id=$1"
                  % config['table'])
        c.execute("PREPARE has_tile(bigint) AS SELECT count(*) FROM %s WHERE id=$1"
                  % config['table'])
        c.execute("""PREPARE set_tile(bigint, bytea) AS
                     UPDATE %s SET pixbuf=$2 WHERE id=$1 AND pixbuf is Null"""
                  % config['table'])

    def get(self, zoom, x, y, fmt):
        c = self.db.cursor()
        if zoom > self.max_zoom:
            shift = zoom - self.max_zoom
            c.execute("EXECUTE has_tile(%s)",
                      (mk_tileid(self.max_zoom, x >> shift, y >> shift), ))
            if c.fetchone()[0]:
                return None
        else:
            c.execute("EXECUTE get_tile(%s)", (mk_tileid(zoom, x, y), ))
            if c.rowcount > 0:
                return c.fetchone()[0]

        return self.empty[fmt]

    def set(self, zoom, x, y, fmt, image=None):
        if zoom <= self.max_zoom:
            c = self.db.cursor()
            c.execute("EXECUTE set_tile(%s, %s)", (mk_tileid(zoom, x, y), image))


class MapnikRenderer(object):
    config = { 'formats' : [ 'png' ],
               'tile_size' : (256, 256),
               'max_zoom' : 18
             }
    stylecfg = {}

    def __init__(self, config, styleconfig, needs_locking=False):
        if config is not None:
            self.config.update(config)
        if styleconfig is not None:
            self.stylecfg.update(styleconfig)

        self.map = mapnik.Map(*self.config['tile_size'])
        if self.config['source_type'] == 'xml':
            src = os.path.join(self.config['source'])
            mapnik.load_map(self.map, src)
        if self.config['source_type'] == 'python':
            __import__(self.config['source'])
            sys.modules[self.config['source']].construct_map(self.map, self.stylecfg)
            print(mapnik.save_map_to_string(self.map))
        self.mproj = mapnik.Projection(self.map.srs)
        self.gproj = TileProjection(self.config['max_zoom'])

        if needs_locking:
            self.map_lock = Lock()
            self.render_image = self._render_with_lock
        else:
            self.render_image = self._render_without_lock

    def split_url(self, zoom, x, y):
        ypt = y.find('.')
        if ypt < 0:
            return None
        tiletype = y[ypt+1:]
        if tiletype not in self.config['formats']:
            return None
        try:
            zoom = int(zoom)
            x = int(x)
            y = int(y[:ypt])
        except ValueError:
            return None

        if zoom > self.config['max_zoom']:
            return None

        return (zoom, x, y, tiletype)

    def render(self, zoom, x, y, fmt):
        p0 = self.gproj.fromTileToLL(zoom, x, y+1)
        p1 = self.gproj.fromTileToLL(zoom, x+1, y)

        c0 = self.mproj.forward(mapnik.Coord(p0[0],p0[1]))
        c1 = self.mproj.forward(mapnik.Coord(p1[0],p1[1]))

        bbox = mapnik.Box2d(c0.x, c0.y, c1.x, c1.y)
        im = mapnik.Image(256, 256)

        self.render_image(bbox, im)

        return im.tostring('png256')

    def _render_with_lock(self, bbox, im):
        with self.map_lock:
            self.map.zoom_to_box(bbox)
            mapnik.render(self.map, im)

    def _render_without_lock(self, bbox, im):
        self.map.zoom_to_box(bbox)
        mapnik.render(self.map, im)


@cherrypy.popargs('zoom', 'x', 'y')
class TileServer(object):
    cachecfg = { 'type' : 'DummyCache'}

    def __init__(self, style, script_name):
        self.style_name = style
        self.script_name = script_name

    def setup(self, app, config, needs_lock):
        if 'TILE_CACHE' in config:
            self.cachecfg.update(config['TILE_CACHE'])
        cacheclass = globals()[self.cachecfg['type']]
        self.cache = cacheclass(self.cachecfg)
        self.renderer = MapnikRenderer(config.get('RENDERER'),
                                       config.get('TILE_STYLE'),
                                       needs_lock)

    @cherrypy.expose
    def test_map(self):
        return DEFAULT_TESTMAP % { 'style' : self.style_name,
                                   'script_name' : self.script_name,
                                   'leaflet_path' : os.environ.get('LEAFLET_PATH', 'http://cdn.leafletjs.com/leaflet-0.7.5')}

    @cherrypy.expose
    @cherrypy.tools.response_headers(headers=[('Content-Type', 'image/png')])
    def index(self, zoom, x, y):
        tile_desc = self.renderer.split_url(zoom, x, y)
        if tile_desc is None:
            raise cherrypy.NotFound()

        tile = self.cache.get(*tile_desc)
        if tile is None:
            tile = self.renderer.render(*tile_desc)
            self.cache.set(*tile_desc, image=tile)

        return tile

def error_page(status, message, traceback, version):
    cherrypy.response.headers['Content-Type'] = 'text/plain'
    return 'Error %s\n\n%s\n' % (status. message)

def setup_sites(sites, needs_lock=False, script_name=''):
    for site in sites:
        try:
            __import__(site)
        except ImportError:
            print("Missing config for site '%s'. Skipping." % site)
            continue

        site_cfg = {}
        for var in dir(sys.modules[site]):
            site_cfg[var] = getattr(sys.modules[site], var)

        basename = site.split('.')[-1]
        server = TileServer(basename, script_name)
        app = cherrypy.tree.mount(server,  script_name + '/' + basename)
        server.setup(app, site_cfg, needs_lock)
    # now disable trailing slash
    cherrypy.config.update({'tools.trailing_slash.on': False })


def application(environ, start_response):
    """ Handler for WSGI appications.
        Must NOT be run with threading enabled."""
    setup_sites(environ['TILE_SITES'].split(','),
                script_name=environ['SCRIPT_NAME'])
    cherrypy.config.update({'log.wsgi' : True,
                            'log.screen' : False,
                            'error_page.default': error_page})
    globals()['application'] = cherrypy.tree
    return cherrypy.tree(environ, start_response)

if __name__ == '__main__':
    setup_sites(os.environ['TILE_SITES'].split(','), needs_lock=True)
    cherrypy.engine.start()
    cherrypy.engine.block()
